"use client";
import {useMemo,useState} from "react";
import {Activity,AlertTriangle,BarChart3,Bell,CalendarDays,CheckCircle2,ChevronRight,ClipboardPlus,Clock3,CreditCard,FileText,HeartPulse,LayoutDashboard,Menu,MessageSquareText,Plus,Search,ShieldCheck,Stethoscope,TestTube2,UserRound,Users,Video,X,Zap} from "lucide-react";
type Patient={id:number;name:string;initials:string;age:number;sex:string;phone:string;condition:string;lastVisit:string;risk:"Low"|"Moderate"|"High";color:string};
const patients:Patient[]=[
{id:1,name:"Ananya Rao",initials:"AR",age:34,sex:"Female",phone:"+91 98450 11220",condition:"Type 2 Diabetes",lastVisit:"Today, 9:30 AM",risk:"Moderate",color:"#0069a8"},
{id:2,name:"Vikram Shetty",initials:"VS",age:61,sex:"Male",phone:"+91 99001 40218",condition:"Hypertension",lastVisit:"Today, 10:15 AM",risk:"High",color:"#7c3aed"},
{id:3,name:"Meera D'Souza",initials:"MD",age:27,sex:"Female",phone:"+91 97420 88411",condition:"Migraine follow-up",lastVisit:"Yesterday",risk:"Low",color:"#0e8a82"},
{id:4,name:"Rohan Kumar",initials:"RK",age:45,sex:"Male",phone:"+91 98861 76432",condition:"Respiratory infection",lastVisit:"11 Sep 2026",risk:"Moderate",color:"#d46b22"},
{id:5,name:"Fatima Khan",initials:"FK",age:52,sex:"Female",phone:"+91 90080 32104",condition:"Thyroid review",lastVisit:"9 Sep 2026",risk:"Low",color:"#be185d"}];
const nav=[["Dashboard",LayoutDashboard],["Patients",Users],["Appointments",CalendarDays],["Consultations",Stethoscope],["Prescriptions",ClipboardPlus],["Lab & Imaging",TestTube2],["Billing",CreditCard],["Messages",MessageSquareText],["Reports",BarChart3]] as const;
function Risk({value}:{value:Patient["risk"]}){return <span className={"risk "+value.toLowerCase()}><i/>{value}</span>}
export default function Home(){
 const[section,setSection]=useState("Dashboard"),[query,setQuery]=useState(""),[active,setActive]=useState<Patient|null>(null),[showNew,setShowNew]=useState(false),[toast,setToast]=useState(""),[mobile,setMobile]=useState(false);
 const filtered=useMemo(()=>patients.filter(p=>(p.name+p.condition+p.phone).toLowerCase().includes(query.toLowerCase())),[query]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2600)};
 return <main className="app-shell">
 <aside className={"sidebar "+(mobile?"open":"")}><div className="brand"><span className="brand-mark"><HeartPulse size={25}/></span><div><b>ROSHsoft</b><small>Intelligent Clinic</small></div><button className="nav-close" onClick={()=>setMobile(false)}><X/></button></div>
 <nav><p className="eyebrow">WORKSPACE</p>{nav.map(([label,Icon])=><button key={label} onClick={()=>{setSection(label);setMobile(false)}} className={section===label?"active":""}><Icon size={19}/><span>{label}</span>{label==="Messages"&&<em>3</em>}</button>)}</nav>
 <div className="secure"><ShieldCheck size={22}/><div><b>Clinic data protected</b><span>Encrypted · Audit enabled</span></div></div><div className="doctor"><div className="avatar">VV</div><div><b>Dr. Vyalarry Vaz</b><span>General Medicine</span></div><ChevronRight size={16}/></div></aside>
 <section className="workspace"><header className="topbar"><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="global-search"><Search size={18}/><input aria-label="Search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patients, records, appointments…"/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-btn"><Bell size={20}/><i/></button><button className="primary" onClick={()=>setShowNew(true)}><Plus size={18}/> New patient</button></div></header>
 <div className="content">{section==="Dashboard"?<><div className="page-head"><div><span className="date">SUNDAY · 13 SEPTEMBER 2026</span><h1>Good morning, Doctor.</h1><p>Here’s what needs your attention today.</p></div><button className="outline" onClick={()=>notify("Clinic report prepared for review")}><FileText size={17}/> Daily report</button></div>
 <div className="metrics"><Metric icon={<CalendarDays/>} tone="blue" label="Today’s appointments" value="12" note="4 remaining"/><Metric icon={<Users/>} tone="teal" label="Patients this month" value="184" note="↑ 12% from August"/><Metric icon={<Clock3/>} tone="purple" label="Awaiting follow-up" value="7" note="3 due today"/><Metric icon={<AlertTriangle/>} tone="coral" label="Clinical alerts" value="3" note="1 high priority"/></div>
 <div className="main-grid"><section className="panel schedule"><PanelTitle title="Today’s schedule" sub="12 appointments · 8 completed" action={()=>setSection("Appointments")}/>
 {[["09:30","Ananya Rao","Diabetes review","Completed","AR"],["10:15","Vikram Shetty","Blood pressure follow-up","In consultation","VS"],["11:00","Meera D'Souza","Migraine follow-up","Waiting","MD"],["11:45","Rohan Kumar","New consultation","Confirmed","RK"]].map((a,i)=><div className={"appointment "+(i===1?"current":"")} key={a[0]}><time>{a[0]}<small>AM</small></time><div className={"mini-avatar c"+i}>{a[4]}</div><div className="appt-info"><b>{a[1]}</b><span>{a[2]}</span></div><span className={"status s"+i}>{i===0&&<CheckCircle2 size={14}/>} {a[3]}</span><button className="more">•••</button></div>)}</section>
 <aside className="right-stack"><section className="panel ai-card"><div className="ai-head"><span><Zap size={19}/></span><div><h3>Clinical intelligence</h3><small>AI-assisted · Doctor reviewed</small></div></div><div className="ai-alert"><AlertTriangle size={18}/><div><b>High-risk follow-up</b><p>Vikram Shetty’s BP trend is above his target range across 3 readings.</p><button onClick={()=>setActive(patients[1])}>Review patient <ChevronRight size={14}/></button></div></div><div className="ai-note"><Activity size={17}/><p><b>3 patients</b> may need medication adherence checks this week.</p></div><p className="disclaimer">AI supports care. The doctor makes every clinical decision.</p></section>
 <section className="panel quick"><h3>Quick actions</h3><div><button onClick={()=>setShowNew(true)}><UserRound/>Add patient</button><button onClick={()=>setSection("Appointments")}><CalendarDays/>Book visit</button><button onClick={()=>notify("Prescription workspace opened")}><ClipboardPlus/>Prescription</button><button onClick={()=>setSection("Messages")}><Video/>Teleconsult</button></div></section></aside></div>
 <section className="panel patients-panel"><PanelTitle title="Recent patients" sub="Updated a few moments ago" action={()=>setSection("Patients")}/><PatientTable rows={filtered.slice(0,4)} onOpen={setActive}/></section></>:<ModuleView title={section} query={query} rows={filtered} onOpen={setActive} onAdd={()=>setShowNew(true)} notify={notify}/>}</div></section>
 {active&&<div className="overlay" onClick={()=>setActive(null)}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}><X/></button><div className="patient-hero"><div className="big-avatar" style={{background:active.color}}>{active.initials}</div><div><h2>{active.name}</h2><p>{active.age} years · {active.sex} · {active.phone}</p><Risk value={active.risk}/></div></div><div className="tabs"><button className="active">Overview</button><button>Timeline</button><button>Documents</button></div><div className="vitals"><div><span>Blood pressure</span><b>148/92</b><small className="danger">Above target</small></div><div><span>Heart rate</span><b>78 bpm</b><small>Normal</small></div><div><span>SpO₂</span><b>98%</b><small>Normal</small></div></div><div className="clinical-note"><span>AI PRE-VISIT SUMMARY</span><h3>{active.condition}</h3><p>Patient is due for a routine review. Recent readings and medication adherence should be discussed. No new allergy alerts recorded.</p></div><h3 className="section-label">Recent care</h3><div className="timeline"><i/><div><b>Follow-up consultation</b><p>Symptoms stable. Continue monitoring and review results.</p><span>{active.lastVisit}</span></div></div><button className="primary wide" onClick={()=>notify("Consultation started securely")}><Stethoscope size={18}/> Start consultation</button></section></div>}
 {showNew&&<div className="overlay center" onClick={()=>setShowNew(false)}><form className="modal" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();setShowNew(false);notify("New patient record saved securely")}}><button type="button" className="close" onClick={()=>setShowNew(false)}><X/></button><span className="modal-icon"><UserRound/></span><h2>Register a new patient</h2><p>Create a secure clinic record. Required fields are marked.</p><label>Full name *<input required placeholder="Patient’s full name"/></label><div className="form-row"><label>Mobile number *<input required placeholder="+91"/></label><label>Date of birth<input type="date"/></label></div><label>Reason for visit<textarea placeholder="Symptoms or primary concern"/></label><label className="consent"><input type="checkbox" required/> Patient consent has been recorded</label><div className="form-actions"><button type="button" className="outline" onClick={()=>setShowNew(false)}>Cancel</button><button className="primary">Save patient</button></div></form></div>}{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}</main>
}
function Metric({icon,tone,label,value,note}:{icon:React.ReactNode;tone:string;label:string;value:string;note:string}){return <article><div className={"metric-icon "+tone}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>}
function PanelTitle({title,sub,action}:{title:string;sub:string;action:()=>void}){return <div className="panel-title"><div><h2>{title}</h2><span>{sub}</span></div><button onClick={action}>View all <ChevronRight size={16}/></button></div>}
function PatientTable({rows,onOpen}:{rows:Patient[];onOpen:(p:Patient)=>void}){return <div className="table-wrap"><table><thead><tr><th>Patient</th><th>Primary concern</th><th>Last visit</th><th>Risk</th><th/></tr></thead><tbody>{rows.map(p=><tr key={p.id} onClick={()=>onOpen(p)}><td><div className="patient-cell"><span style={{background:p.color}}>{p.initials}</span><div><b>{p.name}</b><small>{p.age} yrs · {p.sex}</small></div></div></td><td>{p.condition}</td><td>{p.lastVisit}</td><td><Risk value={p.risk}/></td><td><ChevronRight size={17}/></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No matching patient records.</div>}</div>}
function ModuleView({title,query,rows,onOpen,onAdd,notify}:{title:string;query:string;rows:Patient[];onOpen:(p:Patient)=>void;onAdd:()=>void;notify:(x:string)=>void}){
 const copy:Record<string,[string,string]>={Patients:["Patient records","Search histories, review risk and continue care."],Appointments:["Appointments","Manage in-clinic and remote consultations."],Consultations:["Consultations","Document notes and review clinical decision support."],Prescriptions:["e-Prescriptions","Create, review and send signed prescriptions."],["Lab & Imaging"]:["Lab & imaging","Track orders and incoming diagnostic results."],Billing:["Billing & insurance","Manage invoices, payments and claims."],Messages:["Patient messages","Secure follow-ups, reminders and care updates."],Reports:["Reports & analytics","Understand clinic activity and care continuity."]};const[heading,sub]=copy[title]||[title,"Clinic workspace"];
 if(title==="Patients")return <><div className="page-head"><div><span className="date">CLINICAL RECORDS</span><h1>{heading}</h1><p>{sub}</p></div><button className="primary" onClick={onAdd}><Plus size={17}/> New patient</button></div><section className="panel module"><div className="module-tools"><div className="inline-search"><Search/><span>{query?<>Results for “{query}”</>:"All active patients"}</span></div><button className="outline">Filter</button></div><PatientTable rows={rows} onOpen={onOpen}/></section></>;
 const items:Record<string,string[][]>={Appointments:[["09:30 AM","Ananya Rao","Completed"],["10:15 AM","Vikram Shetty","In consultation"],["11:00 AM","Meera D'Souza","Waiting"],["11:45 AM","Rohan Kumar","Confirmed"],["02:00 PM","Fatima Khan","Confirmed"]],Consultations:[["Vikram Shetty","BP follow-up","Active"],["Meera D'Souza","Migraine review","Waiting"],["Ananya Rao","Diabetes review","Signed"]],Prescriptions:[["RX-2026-1842","Ananya Rao","Sent"],["RX-2026-1841","Vikram Shetty","Draft"],["RX-2026-1840","Meera D'Souza","Sent"]],["Lab & Imaging"]:[["HbA1c","Ananya Rao","Result ready"],["Lipid profile","Vikram Shetty","Pending"],["Thyroid panel","Fatima Khan","Result ready"]],Billing:[["INV-3028","Vikram Shetty","₹850 paid"],["INV-3027","Ananya Rao","₹1,200 paid"],["INV-3026","Meera D'Souza","₹650 due"]],Messages:[["Meera D'Souza","Headache improved after medication","10:42 AM"],["Ananya Rao","Uploaded glucose readings","Yesterday"],["Clinic reminder","7 follow-ups queued","Automated"]],Reports:[["Patient visits","184 this month","↑ 12%"],["Follow-up completion","91%","↑ 4%"],["Average waiting time","11 minutes","↓ 3 min"]]};
 return <><div className="page-head"><div><span className="date">ROSHSOFT CLINIC</span><h1>{heading}</h1><p>{sub}</p></div><button className="primary" onClick={()=>notify("New item created")}><Plus size={17}/> New</button></div><section className="panel module cards-list">{(items[title]||[]).map((x,i)=><button key={i} onClick={()=>notify(title+" item opened")}><span className="list-icon">{title==="Appointments"?<CalendarDays/>:title==="Billing"?<CreditCard/>:title==="Messages"?<MessageSquareText/>:title==="Reports"?<BarChart3/>:<FileText/>}</span><div><b>{x[0]}</b><p>{x[1]}</p></div><em>{x[2]}</em><ChevronRight/></button>)}</section></>}
